### PR TITLE
Option pass span for tracing

### PR DESCRIPTION
**Pull request by kesslerdev**
Add parentSpan for tracing

### CODE REVIEW

**Comment by Hugome** [comment]
I thought about that, but are you sure we can serialize the whole `parentCtx` into redis ? (Unit tests doesn't pass anymore)
For the metrics, the other solution that was in my mind is to pass the parent span id, but the span will be end by the end of the scheduling action before the job end.

**Comment by kesslerdev** [comment]
yes, it's big but it works

**Comment by kesslerdev** [comment]
i'm testing with only span related params

**Review by Hugome — APPROVED** [review]

**Comment by kesslerdev** [comment]
Great! can you also publish a release ?

**Comment by Hugome** [comment]
Done :)

**Comment by kesslerdev** [comment]
Thanks you !

**Pull request merged**
