### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by kesslerdev**
In case of no redis cacher, can set manually a connection

### CODE REVIEW

**Comment by Hugome** [comment]
Yes, great idea
Thanks for the contribution

**Comment by kesslerdev** [comment]
Thanks you for your module but can you publish a version ? 
also 0.14 version of moleculer is released

**Comment by Hugome** [comment]
I will do the changes for the "currentContext" problem #2, update dependencies for the 0.14 and release a new version.

**Comment by Hugome** [comment]
@kesslerdev New version has been released
Be careful this is now a `client` option (Because the `connection` is an internal bullmq class) 
I have put an example into the `README`

**Pull request merged**
